---
inherit_gem:
  eac_rails_gem_support: ".rubocop.yml"
Style/RedundantStringEscape:
  Exclude:
  - lib/redmine_with_git/patches/redmine_git_hosting/gitolite_hook_patch.rb
  - lib/tasks/redmine_with_git.rake
