--- !ruby/hash:ActionController::Parameters
gitolite_user: ${gitolite_user}
gitolite_ssh_private_key: "${redmine_git_hosting_ssh_key}"
gitolite_ssh_public_key: "${redmine_git_hosting_ssh_key}.pub"
gitolite_server_port: '22'
gitolite_global_storage_dir: repositories/
gitolite_recycle_bin_dir: recycle_bin/
gitolite_redmine_storage_dir: ''
gitolite_temp_dir: "/tmp/redmine_git_hosting_${gitolite_user}/"
gitolite_config_file: gitolite.conf
gitolite_config_has_admin_key: 'true'
gitolite_identifier_prefix: redmine_
gitolite_recycle_bin_expiration_time: 24.0
gitolite_log_level: info
git_config_username: Redmine Git Hosting
git_config_email: redmine@example.net
ssh_server_domain: ${address_host}
http_server_domain: ${address_server}
https_server_domain: ${address_server}
http_server_subdir: ''
show_repositories_url: 'true'
gitolite_daemon_by_default: 'false'
gitolite_http_by_default: '1'
download_revision_enabled: 'true'
gitolite_overwrite_existing_hooks: 'true'
gitolite_hooks_are_asynchronous: 'false'
gitolite_hooks_debug: 'false'
gitolite_hooks_url: "${address_scheme}://${address_server}${address_path}"
gitolite_cache_max_time: '86400'
gitolite_cache_max_size: '16'
gitolite_cache_max_elements: '2000'
gitolite_cache_adapter: database
gitolite_notify_by_default: 'false'
gitolite_notify_global_prefix: "[REDMINE]"
gitolite_notify_global_sender_address: redmine@example.net
gitolite_notify_global_include: []
gitolite_notify_global_exclude: []
all_projects_use_git: 'false'
init_repositories_on_create: 'false'
delete_git_repositories: 'true'
hierarchical_organisation: '${git_repositories_hierarchical_organisation}'
gitolite_use_sidekiq: 'false'
unique_repo_identifier: '${git_repositories_unique_repo_identifier}'
gitolite_resync_all_projects: 'false'
gitolite_resync_all_ssh_keys: 'false'
gitolite_flush_cache: 'false'
gitolite_purge_repos: []
